config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: {
    sessions: 'owners/sessions',
    passwords: 'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'spaces#index'
  resources :users, only: [:show]
  resources :owners, only: [:show]
  resources :spaces, only: [:index, :new, :create, :show] do
    resources :reservations, only: [:new, :create, :show, :destroy] do
      resources :events, only: [:new, :create, :show, :update, :destroy]
    end
    collection do
      get 'search'
    end
  end
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :owner
  has_many :reservations
  has_many :events

  validates :name, :purpose, :text, :postal_code, :prefecture, :city, :town, :tel, :access, :number, :start, :finish, presence: true
  validates :name, length: { maximum: 50 }
  validates :title, length: { maximum: 64 }
  validates :text, length: { in: 10..800 }
  validates :postal_code, length: { is: 7 }, numericality: :only_integer
  validates :price, :number, numericality: true

  scope :party, -> { where(purpose: 'パーティー') }
  scope :meeting, -> { where(purpose: '会議') }
  scope :photo, -> { where(purpose: '写真撮影') }
  scope :location, -> { where(purpose: 'ロケ撮影') }
  scope :event, -> { where(purpose: 'イベント') }
  scope :stay, -> { where(purpose: '宿泊') }
  scope :other, -> { where(purpose: 'その他') }

  mount_uploader :image, ImageUploader
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController

  def index
    @spaces = Space.order("created_at DESC").limit(3)
  end

  def new
    @space = Space.new
  end

  def create
    @space = current_owner.spaces.new(space_params)
    if @space.save
      redirect_to root_path, notice: 'スペースを投稿しました'
    else
      flash.now[:alert] = 'スペースの投稿に失敗しました'
      render :new
    end
  end

  def show
    @space = Space.find(params[:id])
    @events = @space.events
  end

  def search
    @spaces = Space.where(purpose: params[:purpose]).order("created_at DESC")
  end

  private

  def space_params
    params.require(:space).permit(:name, :image, :purpose, :text, :start, :finish, :postal_code, :prefecture, :city, :town, :building, :tel, :access, :price, :title, :number).merge(purpose: params[:purpose])
  end
end

app/views/spaces/_cont-space.haml
.cont__space.cont__space--gray
  .cont__space__unit
    %h2.cont__space__unit__title#party パーティー
    %ul.row.clear-fix
      - @spaces.party.each do |space|
        = render space
    .cont__space__unit__more
      - if @spaces.party.last
        = form_tag search_spaces_path, class: 'cont__space__unit__more--button', method: 'get' do
          = hidden_field_tag 'purpose', 'パーティー'
          = submit_tag 'パーティーで利用できるスペースをもっと見る', class: 'cont__space__unit__more__text', name: nil
          %i.fa.fa-angle-right.fa-lg
      - else
        %span.cont__space__unit__more__text.cont__space__unit__more__text--none 利用できるスペースはありません

.cont__space
  .cont__space__unit
    %h2.cont__space__unit__title#meeting 会議
    %ul.row.clear-fix
      - @spaces.meeting.each do |space|
        = render space
    .cont__space__unit__more
      - if @spaces.meeting.last
        = form_tag search_spaces_path, class: 'cont__space__unit__more--button', method: 'get' do
          = hidden_field_tag 'purpose', '会議'
          = submit_tag '会議で利用できるスペースをもっと見る', class: 'cont__space__unit__more__text', name: nil
          %i.fa.fa-angle-right.fa-lg
      - else
        %span.cont__space__unit__more__text.cont__space__unit__more__text--none 利用できるスペースはありません

.cont__space.cont__space--gray
  .cont__space__unit
    %h2.cont__space__unit__title#photo 写真撮影
    %ul.row.clear-fix
      - @spaces.photo.each do |space|
        = render space
    .cont__space__unit__more
      - if @spaces.photo.last
        = form_tag search_spaces_path, class: 'cont__space__unit__more--button', method: 'get' do
          = hidden_field_tag 'purpose', '写真撮影'
          = submit_tag '写真撮影で利用できるスペースをもっと見る', class: 'cont__space__unit__more__text', name: nil
          %i.fa.fa-angle-right.fa-lg
      - else
        %span.cont__space__unit__more__text.cont__space__unit__more__text--none 利用できるスペースはありません

.cont__space
  .cont__space__unit
    %h2.cont__space__unit__title#location ロケ撮影
    %ul.row.clear-fix
      - @spaces.location.each do |space|
        = render space
    .cont__space__unit__more
      - if @spaces.location.last
        = form_tag search_spaces_path, class: 'cont__space__unit__more--button', method: 'get' do
          = hidden_field_tag 'purpose', 'ロケ撮影'
          = submit_tag 'ロケ撮影で利用できるスペースをもっと見る', class: 'cont__space__unit__more__text', name: nil
          %i.fa.fa-angle-right.fa-lg
      - else
        %span.cont__space__unit__more__text.cont__space__unit__more__text--none 利用できるスペースはありません

.cont__space.cont__space--gray
  .cont__space__unit
    %h2.cont__space__unit__title#event イベント
    %ul.row.clear-fix
      - @spaces.event.each do |space|
        = render space
    .cont__space__unit__more
      - if @spaces.event.last
        = form_tag search_spaces_path, class: 'cont__space__unit__more--button', method: 'get' do
          = hidden_field_tag 'purpose', 'イベント'
          = submit_tag 'イベントで利用できるスペースをもっと見る', class: 'cont__space__unit__more__text', name: nil
          %i.fa.fa-angle-right.fa-lg
      - else
        %span.cont__space__unit__more__text.cont__space__unit__more__text--none 利用できるスペースはありません

.cont__space
  .cont__space__unit
    %h2.cont__space__unit__title#stay 宿泊
    %ul.row.clear-fix
      - @spaces.stay.each do |space|
        = render space
    .cont__space__unit__more
      - if @spaces.stay.last
        = form_tag search_spaces_path, class: 'cont__space__unit__more--button', method: 'get' do
          = hidden_field_tag 'purpose', '宿泊'
          = submit_tag '宿泊で利用できるスペースをもっと見る', class: 'cont__space__unit__more__text', name: nil
          %i.fa.fa-angle-right.fa-lg
      - else
        %span.cont__space__unit__more__text.cont__space__unit__more__text--none 利用できるスペースはありません

.cont__space.cont__space--gray
  .cont__space__unit
    %h2.cont__space__unit__title#other その他
    %ul.row.clear-fix
      - @spaces.other.each do |space|
        = render space
    .cont__space__unit__more
      - if @spaces.other.last
        = form_tag search_spaces_path, class: 'cont__space__unit__more--button', method: 'get' do
          = hidden_field_tag 'purpose', 'その他'
          = submit_tag 'その他で利用できるスペースをもっと見る', class: 'cont__space__unit__more__text', name: nil
          %i.fa.fa-angle-right.fa-lg
      - else
        %span.cont__space__unit__more__text.cont__space__unit__more__text--none 利用できるスペースはありません

app/views/spaces/_cont-top.haml
.cont__top
  .cont__top__logo
    = image_tag '//cdn.spacemarket.net/assets/service/logo-1ca6e86ca1d6dca0e0cffec09d775936.svg'
  %h1.cont__top__text
    = "#{@spaces.length}件のレンタルスペースから目的に合ったスペースをかんたん予約"

app/views/spaces/_cont-type.haml
.cont__type.clear-fix
  %ul.row
    %li.cont__type__list.cont__type__list--up
      = link_to '#party', class: 'cont__type__list__button' do
        = image_tag '//cdn.spacemarket.net/assets/service/top/party_blue-cb3572688faf3bc72aa4dd199af8ccc0.svg', class: 'cont__type__list__button__logo'
        %span.cont__type__list__button__name
          パーティー
          %span.cont__type__list__button__number
            = "#{@spaces.party.length}件"
        %i.fa.fa-angle-right.fa-lg
    %li.cont__type__list.cont__type__list--up
      = link_to '#meeting', class: 'cont__type__list__button' do
        = image_tag '//cdn.spacemarket.net/assets/service/top/class_blue-00162a2a729689f5de5738a85dd80ab6.svg', class: 'cont__type__list__button__logo'
        %span.cont__type__list__button__name
          会議
          %span.cont__type__list__button__number
            = "#{@spaces.meeting.length}件"
        %i.fa.fa-angle-right.fa-lg
    %li.cont__type__list.cont__type__list--up
      = link_to '#photo', class: 'cont__type__list__button' do
        = image_tag '//cdn.spacemarket.net/assets/service/top/photo_shoot_blue-d21ffcb8822c210acb072f45652ea485.svg', class: 'cont__type__list__button__logo'
        %span.cont__type__list__button__name
          写真撮影
          %span.cont__type__list__button__number
            = "#{@spaces.photo.length}件"
        %i.fa.fa-angle-right.fa-lg
    %li.cont__type__list.cont__type__list--down
      = link_to '#location', class: 'cont__type__list__button' do
        = image_tag '//cdn.spacemarket.net/assets/service/top/film_shoot_blue-ff1cb442bb7be4842fff66050387e5f6.svg', class: 'cont__type__list__button__logo'
        %span.cont__type__list__button__name
          ロケ撮影
          %span.cont__type__list__button__number
            = "#{@spaces.location.length}件"
        %i.fa.fa-angle-right.fa-lg
    %li.cont__type__list.cont__type__list--down
      = link_to '#event', class: 'cont__type__list__button' do
        = image_tag '//cdn.spacemarket.net/assets/service/top/event_blue-1e06c16bfec922e6f4ede5e6e318fa83.svg', class: 'cont__type__list__button__logo'
        %span.cont__type__list__button__name
          イベント
          %span.cont__type__list__button__number
            = "#{@spaces.event.length}件"
        %i.fa.fa-angle-right.fa-lg
    %li.cont__type__list.cont__type__list--down
      = link_to '#stay', class: 'cont__type__list__button' do
        = image_tag '//cdn.spacemarket.net/assets/service/top/stay_blue-a1dea4fb5baa0aea1deee671c470cb21.svg', class: 'cont__type__list__button__logo'
        %span.cont__type__list__button__name
          宿泊
          %span.cont__type__list__button__number
            = "#{@spaces.stay.length}件"
        %i.fa.fa-angle-right.fa-lg
    %li.cont__type__list.cont__type__list--down
      = link_to '#other', class: 'cont__type__list__button' do
        = image_tag '//cdn.spacemarket.net/assets/service/top/other_blue-b01238da3b714563414031d17516c21b.svg', class: 'cont__type__list__button__logo'
        %span.cont__type__list__button__name
          その他
          %span.cont__type__list__button__number
            = "#{@spaces.other.length}件"
        %i.fa.fa-angle-right.fa-lg

app/views/spaces/_header-nav.haml
%li.header__nav__list
  - if owner_signed_in?
    .more
      .header__nav__list__button
        %p.header__nav__list__link
          スペースを掲載する
          %i.fa.fa-sort-desc
      %ul.more__list
        %li
          = link_to new_space_path do
            %p.more__list__text スペース投稿
        %li
          = link_to owner_path(current_owner) do
            %p.more__list__text マイページ
        %li
          = link_to destroy_owner_session_path, method: 'delete' do
            %p.more__list__text ログアウト
  - else
    .more
      = link_to '', class: 'header__nav__list__button' do
        スペースを掲載する
        %i.fa.fa-sort-desc
      %ul.more__list
        %li
          = link_to new_owner_registration_path do
            %p.more__list__text 新規登録
        %li
          = link_to new_owner_session_path do
            %p.more__list__text ログイン
%li.header__nav__list
  = link_to root_path do
    %i.fa.fa-envelope.fa-lg
%li.header__nav__list
- if user_signed_in?
  .more
    %li.header__nav__list
      %p.header__nav__list__link
        = current_user.name
        %i.fa.fa-sort-desc
      %ul.more__list
        %li
          = link_to user_path(current_user) do
            %p.more__list__text マイページ
        %li
          = link_to destroy_user_session_path, method: 'delete' do
            %p.more__list__text ログアウト
  %li.header__nav__list.header__nav__list--image
    = image_tag "#{current_user.image}", class: 'header__nav__list--image--this'
- else
  %li.header__nav__list
    = link_to new_user_registration_path do
      新規登録
  %li.header__nav__list
    = link_to new_user_session_path do
      ログイン

app/views/spaces/_header-top.haml
.header
  .header__top
    .header__top__circle
      %p.header__top__circle__text
        2017年
        %br
        6月30日
        %br
        まで
    %p.header__top__body アプリからの予約でスペース利用料が3,000円OFF！いつでも、どこでもレンタルスペースを検索、予約！
    %p.header__top__camp キャンペーン詳細へ

app/views/spaces/_space.haml
%li.cont__space__unit__main.cont__space__unit__main--3
  = link_to space_path(space) do
    .cont__space__unit__main--button
      .cont__space__unit__main__column.cont__space__unit__main__column--3
        = image_tag "#{space.image}", class: 'cont__space__unit__main__column__image cont__space__unit__main__column__image--3'
        %span.cont__space__unit__main__column__price
          = "¥#{space.price}/時間"
      .cont__space__unit__main__column__body
        %h3.cont__space__unit__main__column__body__intro
          = space.text
        %ul.clear-fix
          %li.cont__space__unit__main__column__body__data
            %i.fa.fa-user
            %span.cont__space__unit__main__column__data__body__people
              = space.number
          %li.cont__space__unit__main__column__body__data
            %i.fa.fa-map-marker
            %span.cont__space__unit__main__column__body__sdata__access
              = "#{space.prefecture}#{space.city}"

app/views/spaces/index.html.haml
.header
  =render 'header-top'
  .header__nav.clear-fix
    %ul.row
      =render 'header-nav'

.cont
  =render 'cont-top'
  =render 'cont-type'
  =render 'cont-space'

app/views/spaces/new.haml
.header__nav.clear-fix
  %ul.row
    = render 'spaces/header-nav'
  .header__nav__logo
    = link_to root_path do
      = image_tag '//cdn.spacemarket.net/assets/service/logo-1ca6e86ca1d6dca0e0cffec09d775936.svg'

.my-page
  = render '/owners/owner-top'

.space-form.clear-fix
  .space-form__left
    %h1.space-form__left__title 会場を追加
    = link_to '#link-to-basis' do
      %h2.space-form__left__nav 基本情報
    = link_to '#link-to-access' do
      %h2.space-form__left__nav 住所・アクセス
  .space-form__right
    = form_for @space do |f|
      .space-form__right__title#link-to-basis
        %span.space-form__right__title__term.space-form__right__title__term--free 任意
        %span.space-form__right__title__text カバー写真
        %span.space-form__right__title__plus 外観や会場全体を表す画像ををアップロードして下さい。
      .space-form__right__field
        = f.label :image, class: 'space-form__right__field__image' do
          = f.file_field :image, class: 'space-form__right__field__image__button', style: 'display:none;'
          %i.fa.fa-camera.fa-3x
          %p.space-form__right__field__image__text カバー写真を選択
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 名称
        %span.space-form__right__title__plus 50文字以内。会場・建物名を入力してください。
      .space-form__right__field
        = f.text_field :name, class: 'space-form__right__field__name w500', placeholder: 'スペースマーケット、渋谷ビル等'
      .space-form__right__title
        %span.space-form__right__title__term.space-form__right__title__term--free 任意
        %span.space-form__right__title__text スペースの見出し
        %span.space-form__right__title__plus 64文字以内。未入力時は会場名と同じ。
      .space-form__right__field
        = text_field_tag 'space[title]', nil, {placeholder: 'スペースマーケット、渋谷ビル等', class: 'space-form__right__field__name w500'}
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 会場の用途
      .space-form__right__field
        = f.label :purpose, class: 'space-form__right__field__type', for: 'button-party' do
          = radio_button_tag :purpose, 'パーティー', class: 'space-form__right__field__type__radio', id: 'button-party'
          パーティー
        = f.label :purpose, class: 'space-form__right__field__type', for: 'button-meeting' do
          = radio_button_tag :purpose, '会議', class: 'space-form__right__field__type__radio', id: 'button-meeting'
          会議
        = f.label :purpose, class: 'space-form__right__field__type', for: 'button-photo' do
          = radio_button_tag :purpose, '写真撮影', class: 'space-form__right__field__type__radio', id: 'button-photo'
          写真撮影
        = f.label :purpose, class: 'space-form__right__field__type', for: 'button-location' do
          = radio_button_tag :purpose, 'ロケ撮影', class: 'space-form__right__field__type__radio', id: 'button-location'
          ロケ撮影
        = f.label :purpose, class: 'space-form__right__field__type', for: 'button-event' do
          = radio_button_tag :purpose, 'イベント', class: 'space-form__right__field__type__radio', id: 'button-event'
          イベント
        = f.label :purpose, class: 'space-form__right__field__type', for: 'button-hotel' do
          = radio_button_tag :purpose, '宿泊', class: 'space-form__right__field__type__radio', id: 'button-hotel'
          宿泊
        = f.label :purpose, class: 'space-form__right__field__type', for: 'button-others' do
          = radio_button_tag :purpose, 'その他', class: 'space-form__right__field__type__radio', id: 'button-others'
          その他
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 会場について
        %span.space-form__right__title__plus 10文字以上800文字以内。
      .space-form__right__field
        = f.text_area :text, class: 'space-form__right__field__text', placeholder: '大きな窓から入る自然光が印象的なスタジオです。イベントやセミナーはもちろん、撮影、展示会にも利用いただけます。'
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 営業時間について
      .space-form__right__field
        %span
          = f.text_field :start, class: 'space-form__right__field__time', placeholder: '9'
        %span :00〜
        %span
          = f.text_field :finish, class: 'space-form__right__field__time', placeholder: '18'
        %span :00
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 料金
        %span.space-form__right__title__plus 1時間当たり、半角数字のみ。
      .space-form__right__field
        %span ¥
        = f.text_field :price, class: 'space-form__right__field__price w110', placeholder: '5000'
        %span /時間
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 収容人数
        %span.space-form__right__title__plus 半角数字のみ。
      .space-form__right__field
        %span 〜
        = f.text_field :number, class: 'space-form__right__field__price w110', placeholder: '30'
        %span 人
      .space-form__right__title#link-to-access
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 郵便番号
        %span.space-form__right__title__plus ハイフン無しの半角数字。
      .space-form__right__field
        = f.text_field :postal_code, class: 'space-form__right__field__postal w110', placeholder: '1600023'
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 都道府県・市区町村
      .space-form__right__field
        = f.label :prefecture, class: 'space-form__right__field__prefecture--label' do
          = f.select :prefecture, [["東京都", "東京都"], ["神奈川県", "神奈川県"], ["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉県", "千葉県"], ["新潟県", "新潟県"], ["富山県", "富山県"], ["石川県", "石川県"], ["福井県", "福井県"], ["山梨県", "山梨県"], ["長野県", "長野県"], ["岐阜県", "岐阜県"], ["静岡県", "静岡県"], ["愛知県", "愛知県"], ["三重県", "三重県"], ["滋賀県", "滋賀県"], ["京都府", "京都府"], ["大阪府", "大阪府"], ["兵庫県", "兵庫県"], ["奈良県", "奈良県"], ["和歌山県", "和歌山県"], ["鳥取県", "鳥取県"], ["島根県", "島根県"], ["岡山県", "岡山県"], ["広島県", "広島県"], ["山口県", "山口県"], ["徳島県", "徳島県"], ["香川県", "香川県"], ["愛媛県", "愛媛県"], ["高知県", "高知県"], ["福岡県", "福岡県"], ["佐賀県", "佐賀県"], ["長崎県", "長崎県"], ["熊本県", "熊本県"], ["大分県", "大分県"], ["宮崎県", "宮崎県"], ["鹿児島県", "鹿児島県"], ["沖縄県", "沖縄県"]], {}, { class: 'space-form__right__field__prefecture' }
          %i.fa.fa-sort-desc
        = f.text_field :city, class: 'space-form__right__field__city', placeholder: '新宿区'
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 町名・番地
      .space-form__right__field
        = f.text_field :town, class: 'space-form__right__field__town', placeholder: '西新宿6-15-1'
      .space-form__right__title
        %span.space-form__right__title__term.space-form__right__title__term--free 任意
        %span.space-form__right__title__text ビル名・部屋番号
      .space-form__right__field
        = f.text_field :building, class: 'space-form__right__field__building w500', placeholder: 'ラ・トゥール新宿608号室'
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text 電話番号
        %span.space-form__right__title__plus この情報は予約が確定次第ゲストに送信される利用日程表で開示されます。
      .space-form__right__field
        = f.text_field :tel, class: 'space-form__right__field__tel w500', placeholder: '03-1234-5678'
      .space-form__right__title
        %span.space-form__right__title__term 必須
        %span.space-form__right__title__text アクセス
        %span.space-form__right__title__plus 最寄駅からの歩き方や高速道路の出口、所要時間などを入力してください。
      .space-form__right__field
        = f.text_area :access, class: 'space-form__right__field__access', placeholder: 'JR新宿駅西口より徒歩7分'
      .space-form__right__field
        .space-form__right__field__submit
          = f.submit '送信', class: 'space-form__right__field__submit__button'

app/views/spaces/search.haml
.header
  =render 'header-top'
  .header__nav.clear-fix
    %ul.row
      =render 'spaces/header-nav'
    .header__nav__logo
      = link_to root_path do
        = image_tag '//cdn.spacemarket.net/assets/service/logo-1ca6e86ca1d6dca0e0cffec09d775936.svg'

.cont__space.cont__space--top
  .cont__space__unit
    %h2.cont__space__unit__title#party
      = @spaces.first.purpose
    %ul.row.clear-fix
      - @spaces.each do |space|
        = render space

app/views/spaces/show.html.haml
.header
  =render 'header-top'
  .header__nav.clear-fix
    %ul.row
      =render 'spaces/header-nav'
    .header__nav__logo
      = link_to root_path do
        = image_tag '//cdn.spacemarket.net/assets/service/logo-1ca6e86ca1d6dca0e0cffec09d775936.svg'

.space
  %P.space__intro
    - if @space.title != ''
      = @space.title
    - else
      = @space.name
  .space__image
    = image_tag "#{@space.image}", class: 'space__image__this', alt: 'main-image'
  .space__info
    .space__info__nav
      .space__info__nav__main
        %ul.clear-fix
          %li.space__info__nav__main__list
            = link_to '#title-buttom' do
              概要
          %li.space__info__nav__main__list
            = link_to '#access-buttom' do
              アクセス
          %li.space__info__nav__main__list
            = link_to '#event-buttom' do
              イベント
    .space__info__title
      .space__info__title__wrapper
        .space__info__title__wrapper__main
          %h1.space__info__title__wrapper__main__name#title-buttom
            - if @space.title != ''
              = @space.title
            - else
              = @space.name
          %ul.clear-fix
            %li.space__info__title__wrapper__main__list
              %i.fa.fa-building
              %span.space__info__title__wrapper__main__list__text
                = @space.name
            %li.space__info__title__wrapper__main__list
              %i.fa.fa-user
              %span.space__info__title__wrapper__main__list__text
                = "〜#{@space.number}人"
            %li.space__info__title__wrapper__main__list
              %i.fa.fa-map-marker
              %span.space__info__title__wrapper__main__list__text
                = "#{@space.prefecture}#{@space.city}"
            %li.space__info__title__wrapper__main__list
              %i.fa.fa-folder
              %span.space__info__title__wrapper__main__list__text
                = @space.purpose
    .space__info__detail
      .space__info__detail__wrapper
        .space__info__detail__wrapper__body.clear-fix
          .space__info__detail__wrapper__body__about
            %h2 会場について
          .space__info__detail__wrapper__body__text
            %p
              = simple_format(@space.text)
        .space__info__detail__wrapper__body.clear-fix
          .space__info__detail__wrapper__body__about
            %h2 収容人数
          .space__info__detail__wrapper__body__text
            %p
              = "〜#{@space.number}人"
        .space__info__detail__wrapper__body.clear-fix
          .space__info__detail__wrapper__body__about
            %h2 営業時間
          .space__info__detail__wrapper__body__text
            %p
              = "#{@space.start}:00〜#{@space.finish}:00"
        .space__info__detail__wrapper__body.clear-fix
          .space__info__detail__wrapper__body__about#price-buttom
            %h2 価格
          .space__info__detail__wrapper__body__text
            %p.space__info__detail__wrapper__body__text--bold
              = "¥#{@space.price}/時間"
        .space__info__detail__wrapper__side
          .space__info__detail__wrapper__side__request
            %span.space__info__detail__wrapper__side__request__price--bold
              = "¥#{@space.price}"
            %span.space__info__detail__wrapper__side__request__price /時間
            - if user_signed_in?
              = link_to new_space_reservation_path(@space) do
                %p.space__info__detail__wrapper__side__request__button 予約リクエスト
            - else
              = link_to new_user_session_path do
                %p.space__info__detail__wrapper__side__request__button 予約リクエスト
          .space__info__detail__wrapper__side__owner
            = image_tag "#{@space.owner.image}", class: 'space__info__detail__wrapper__side__owner__image', alt: 'owner-image'
            %p.space__info__detail__wrapper__side__owner__intro このスペースの管理者
            %p.space__info__detail__wrapper__side__owner__name
              = @space.owner.name
    .space__info__access
      .space__info__access__wrapper
        .space__info__access__wrapper__body.clear-fix#access-buttom
          %p.space__info__access__wrapper__body__name 住所
          %p.space__info__access__wrapper__body__text
            = "#{@space.prefecture}#{@space.city}#{@space.town}#{@space.building}"
        .space__info__access__wrapper__body.clear-fix
          %p.space__info__access__wrapper__body__name アクセス
          %p.space__info__access__wrapper__body__text
            = @space.access

    .space__info__detail#event-buttom
      .space__info__detail__wrapper
        .space__info__detail__wrapper__event
          %h2.space__info__detail__wrapper__event--text 開催予定のイベント
          - if @events.last
            - @events.each do |event|
              - if event.reservation.year.to_i >= Date.today.strftime('%y').to_i && event.reservation.month.to_i >= Date.today.strftime('%m').to_i && event.reservation.day.to_i >= Date.today.strftime('%d').to_i
                .space__info__detail__wrapper__event__list
                  .space__info__detail__wrapper__event__list--image
                    = image_tag "#{event.users.first.image}", class: 'space__info__detail__wrapper__side__owner__image'
                  .space__info__detail__wrapper__event__list__body
                    %span.space__info__detail__wrapper__event__list__body--host
                      = event.users.first.name
                    %span.space__info__detail__wrapper__event__list__body--time.clear
                      = "20#{event.reservation.year}/#{event.reservation.month}/#{event.reservation.day} #{event.reservation.start}:00〜#{event.reservation.finish}:00"
                    %p.space__info__detail__wrapper__event__list__body--name
                      = link_to space_reservation_event_path(@space, event.reservation, event) do
                        = event.name
          - else
            %p.space__info__detail__wrapper__event--none イベントはありません