config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: {
    sessions: 'owners/sessions',
    passwords: 'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'spaces#index'
  resources :users, only: [:show]
  resources :owners, only: [:show]
  resources :spaces, only: [:index, :new, :create, :show] do
    resources :reservations, only: [:new, :create, :show, :destroy] do
      resources :events, only: [:new, :create, :show, :update, :destroy]
    end
    collection do
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reservations
  has_many :event_users
  has_many :events, through: :event_users

  mount_uploader :image, ImageUploader
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @reservations = @user.reservations.order(year: :asc, month: :asc, day: :asc, start: :asc)
    @events = @user.events
  end
end

app/views/users/_user-top.haml
.my-page__top
  %ul.my-page__top__left
    %li.my-page__top__left__list.my-page__top__left__list--image
      = image_tag "#{@user.image}", class: 'my-page__body__left__image--this'
    %li.my-page__top__left__list
      = @user.name
  %ul.my-page__top__right.clear-fix
    %li
      = link_to edit_user_registration_path do
        %p.my-page__top__right__list 設定
    %li
      = link_to user_path(@user) do
        %p.my-page__top__right__list マイページ

app/views/users/show.haml
.header__nav.clear-fix
  %ul.row
    = render 'spaces/header-nav'
  .header__nav__logo
    = link_to root_path do
      = image_tag '//cdn.spacemarket.net/assets/service/logo-1ca6e86ca1d6dca0e0cffec09d775936.svg'

.my-page
  = render 'user-top'
  .my-page__body
    .my-page__body__left.clear-fix
      .my-page__body__left__image
        = image_tag "#{@user.image}", class: 'my-page__body__left__image--this'
      .my-page__body__left__name
        = @user.name
      = link_to edit_user_registration_path do
        %p.my-page__body__left__edit プロフィールを編集
    .my-page__body__right.clear-fix
      .my-page__body__right--float
        .my-page__body__right__title
          予約一覧
        .my-page__body__right__text
          - if @reservations.last
            - @reservations.each do |reservation|
              - if reservation.year.to_i >= Date.today.strftime('%y').to_i && reservation.month.to_i >= Date.today.strftime('%m').to_i && reservation.day.to_i >= Date.today.strftime('%d').to_i
                = link_to space_reservation_path(reservation.space.id, reservation.id) do
                  %p.my-page__body__right__text--name
                    = reservation.space.name
                  %p.my-page__body__right__text--date
                    = "20#{reservation.year}/#{reservation.month}/#{reservation.day} #{reservation.start}:00〜#{reservation.finish}:00"
          - else
            %p.my-page__body__right__text--none 予約はありません。
      .my-page__body__right--float
        .my-page__body__right__title
          イベント一覧
        .my-page__body__right__text
          - if @events.last
            - @events.each do |event|
              - if event.reservation.year.to_i >= Date.today.strftime('%y').to_i && event.reservation.month.to_i >= Date.today.strftime('%m').to_i && event.reservation.day.to_i >= Date.today.strftime('%d').to_i
                = link_to space_reservation_event_path(event.space, event.reservation, event) do
                  %p.my-page__body__right__text--name
                    = event.name
                  %p.my-page__body__right__text--date
                    = "20#{event.reservation.year}/#{event.reservation.month}/#{event.reservation.day} #{event.reservation.start}:00〜#{event.reservation.finish}:00"
          - else
            %p.my-page__body__right__text--none イベントはありません。