config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: {
    sessions: 'owners/sessions',
    passwords: 'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'spaces#index'
  resources :users, only: [:show]
  resources :owners, only: [:show]
  resources :spaces, only: [:index, :new, :create, :show] do
    resources :reservations, only: [:new, :create, :show, :destroy] do
      resources :events, only: [:new, :create, :show, :update, :destroy]
    end
    collection do
      get 'search'
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :space
  has_one :event

  validates :year, :month, :day, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
    @space = Space.find(params[:space_id])
  end

  def create
    @reservation = current_user.reservations.new(reservation_params)
    @space = Space.find(params[:space_id])
    if @reservation.save
      respond_to do |format|
        format.html { redirect_to space_reservation_path(@space, @reservation), notice: 'スペースを予約しました' }
        format.json { render json: @reservation }
      end
    else
      flash.now[:alert] = 'スペースの予約に失敗しました'
      render :new
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @space = @reservation.space
  end

  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy if reservation.user_id == current_user.id
    redirect_to user_path(current_user)
  end

  private

  def reservation_params
    params.permit(:year, :month, :day, :start, :finish, :price, times: []).merge(space_id: params[:space_id])
  end
end

app/views/reservations/create.haml
.header
  =render 'spaces/header-top'
  .header__nav.clear-fix
    %ul.row
      =render 'spaces/header-nav'
    .header__nav__logo
      = link_to root_path do
        = image_tag '//cdn.spacemarket.net/assets/service/logo-1ca6e86ca1d6dca0e0cffec09d775936.svg'

.reservation.clear-fix
  .reservation__left
    .reservation__left__info.clear-fix
      %p.reservation__left__info__title 予約したスペース
      = link_to space_path(@space), class: 'reservation__left__info__body' do
        = image_tag "#{@space.image}", class: 'reservation__left__info__body__image'
        %p.reservation__left__info__body__text
          = @space.body
  .reservation__right
    %h2.reservation__right__title 予約内容確認
    .reservation__right__confirm
      .reservation__right__confirm__body.clear-fix
        %p.reservation__right__confirm__body__title 利用期間
        %p.reservation__right__confirm__body__text
          = "#{@reservation.year}/#{@reservation.month}/#{@reservation.day} #{@reservation.start}:00〜#{@reservation.finish}:00"
      .reservation__right__confirm__body.clear-fix
        %p.reservation__right__confirm__body__title 料金
        .reservation__right__confirm__body__text
          %p.reservation__right__confirm__body__text--price
            = "¥#{@space.price * (@reservation.finish - @reservation.start)}"
          %p.reservation__right__confirm__body__text--sub
            = "(税込価格 ¥#{(@space.price * (@reservation.finish - @reservation.start) * 1.08).round})"
      .reservation__right__confirm__button.clear-fix
        = link_to root_path do
          %p.reservation__right__confirm__button__text.reservation__right__confirm__button__text--top トップページへ
        = link_to user_path(current_user) do
          %p.reservation__right__confirm__button__text.reservation__right__confirm__button__text--user マイページへ

app/views/reservations/new.haml
= javascript_include_tag "reservation"
.header
  =render 'spaces/header-top'
  .header__nav.clear-fix
    %ul.row
      =render 'spaces/header-nav'
    .header__nav__logo
      = link_to root_path do
        = image_tag '//cdn.spacemarket.net/assets/service/logo-1ca6e86ca1d6dca0e0cffec09d775936.svg'

.container
  .reservation.clear-fix
    .reservation__left
      .reservation__left__info.clear-fix
        %p.reservation__left__info__title 選択中のスペース
        = link_to space_path(@space), class: 'reservation__left__info__body', data: {start: "#{@space.start}", finish: "#{@space.finish}", spaceid: "#{@space.id}", price: "#{@space.price}"} do
          = image_tag "#{@space.image}", class: 'reservation__left__info__body__image'
          %p.reservation__left__info__body__text
            - if @space.title != ''
              = @space.title
            - else
              = @space.name
    .reservation__right
      %h2.reservation__right__title 空き状況の確認／予約リクエスト
      %h3.reservation__right__form__title 料金
      .reservation__right__price
        %span.reservation__right__price--yen
          = "¥#{@space.price}"
        %span.reservation__right__price--time /時間
      = form_for [@space, @reservation], html: { class: 'js-form' } do |f|
        .reservation__right__form
          %h3.reservation__right__form__title 利用期間
          .reservation__right__form__date
            %table
              - today = Date.today
              %caption.reservation__right__form__date__month
                = today.strftime('%Y年%m月')
              %tr.reservation__right__form__date__week
                %th.reservation__right__form__date__week__name 日
                %th.reservation__right__form__date__week__name 月
                %th.reservation__right__form__date__week__name 火
                %th.reservation__right__form__date__week__name 水
                %th.reservation__right__form__date__week__name 木
                %th.reservation__right__form__date__week__name 金
                %th.reservation__right__form__date__week__name 土
              - month = today.strftime('%m')
              - d = today.at_beginning_of_month.at_beginning_of_week(:sunday)
              - 1.upto(5).each do |i|
                %tr.reservation__right__form__date__day
                  - (d..d.end_of_week(:sunday)).each do|c|
                    - if c.strftime('%d') > today.strftime('%d') && c.strftime('%m') == month
                      %td.reservation__right__form__date__day__name
                        = link_to '#time-list', class: 'time-list-button', data: {year: "#{c.strftime('%y')}", month: "#{c.strftime('%m')}", day: "#{c.strftime('%d')}"} do
                          %p.reservation__right__form__date__day__name--day
                            = c.strftime('%d')
                          %p.reservation__right__form__date__day__name--price
                            = "¥#{@space.price}"
                    - elsif c.strftime('%m') == month
                      %td.reservation__right__form__date__day__name.reservation__right__form__date__day__name--gray
                        %p.reservation__right__form__date__day__name--day.reservation__right__form__date__day__name--day--gray
                          = c.strftime('%d')
                        %p.reservation__right__form__date__day__name--price.reservation__right__form__date__day__name--price--gray
                          不可
                    - else
                      %td.reservation__right__form__date__day__name
                - d = d + 1.week
            %ul.reservation__right__form__date__time.hidden#time-list
              - for i in 0..23 do
                = link_to '#time-list', class: "time-select-button time-#{i}", data: {time: "#{i}"} do
                  %li.reservation__right__form__date__time__list.clear-fix
                    %p.reservation__right__form__date__time__list--circle
                      %i.fa.fa-circle-o
                    .reservation__right__form__date__time__list__right
                      %p.reservation__right__form__date__time__list__right--time
                        = "#{i}:00 - #{i+1}:00"
                      %p.reservation__right__form__date__time__list__right--price
                        = "¥#{@space.price}"
        .reservation__right__form.clear-fix.hidden
          .reservation__right__form__submit
            = f.submit '予約リクエストを送信', class: 'reservation__right__form__submit__button'
          .reservation__right__form__submit
            = link_to new_space_reservation_path(@space), class: 'reservation__right__form__submit__button reservation__right__form__submit__button--cancel' do
              日時変更
      .reservation__right__conf.hidden
        %h2.reservation__right__title 予約内容確認
        .reservation__right__confirm
          .reservation__right__confirm__body.clear-fix
            %p.reservation__right__confirm__body__title 利用期間
            %p.reservation__right__confirm__body__text.reservation__right__confirm__body__text--times
          .reservation__right__confirm__body.clear-fix
            %p.reservation__right__confirm__body__title 料金
            .reservation__right__confirm__body__text
              %p.reservation__right__confirm__body__text--price
              %p.reservation__right__confirm__body__text--sub
          .reservation__right__confirm__button.clear-fix
            = link_to root_path do
              %p.reservation__right__confirm__button__text.reservation__right__confirm__button__text--top トップページへ
            = link_to user_path(current_user) do
              %p.reservation__right__confirm__button__text.reservation__right__confirm__button__text--user マイページへ

app/views/reservations/show.haml
.header
  =render 'spaces/header-top'
  .header__nav.clear-fix
    %ul.row
      =render 'spaces/header-nav'
    .header__nav__logo
      = link_to root_path do
        = image_tag '//cdn.spacemarket.net/assets/service/logo-1ca6e86ca1d6dca0e0cffec09d775936.svg'

.container
  .reservation.clear-fix
    .reservation__left
      .reservation__left__info.clear-fix
        %p.reservation__left__info__title 予約したスペース
        = link_to space_path(@space), class: 'reservation__left__info__body' do
          = image_tag "#{@space.image}", class: 'reservation__left__info__body__image'
          %p.reservation__left__info__body__text
            - if @space.title != ''
              = @space.title
            - else
              = @space.name
    .reservation__right
      %h2.reservation__right__title 予約内容確認
      .reservation__right__confirm
        .reservation__right__confirm__body.clear-fix
          %p.reservation__right__confirm__body__title 利用期間
          %p.reservation__right__confirm__body__text
            = "#{@reservation.year}/#{@reservation.month}/#{@reservation.day} #{@reservation.start}:00〜#{@reservation.finish}:00"
        .reservation__right__confirm__body.clear-fix
          %p.reservation__right__confirm__body__title 料金
          .reservation__right__confirm__body__text
            %p.reservation__right__confirm__body__text--price
              = "¥#{@space.price * (@reservation.finish - @reservation.start)}"
            %p.reservation__right__confirm__body__text--sub
              = "(税込価格 ¥#{(@space.price * (@reservation.finish - @reservation.start) * 1.08).round})"
        .reservation__right__confirm__button.clear-fix
          - if @reservation.event
            = link_to space_reservation_event_path(@space, @reservation, @reservation.event) do
              %p.reservation__right__confirm__button__text.reservation__right__confirm__button__text--top イベント詳細
          - else
            = link_to new_space_reservation_event_path(@space, @reservation) do
              %p.reservation__right__confirm__button__text.reservation__right__confirm__button__text--top イベント作成
          = link_to user_path(current_user) do
            %p.reservation__right__confirm__button__text.reservation__right__confirm__button__text--user マイページへ
          - if @reservation.event
          - else
            = link_to "/spaces/#{@space.id}/reservations/#{@reservation.id}", method: 'delete' do
              %p.reservation__right__confirm__button__text.reservation__right__confirm__button__text--cancel 予約取り消し